name: "Hexagonal Architecture Python CI"

on: [push]

jobs:
  buildDockerImage:
    name: Realizando build da imagem Docker
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hexagonal-architecture-python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Test Docker image
        run: docker run $IMAGE_NAME sh -c "python --version"

  buildAndUnitTest:
    name: Rodando testes unitários
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest faker coverage pytest-cov
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Test Coverage with pytest
        run: |
          pytest --cov-config=.coveragerc --cov-report=xml --doctest-modules --cov=. src/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage.xml

  codeQualitySonarScan:
    name: Analisando qualidade do código com SonarQube
    needs: buildAndUnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download code coverage results
        uses: actions/download-artifact@v2

      - name: "Move coverage file to correct folder"
        shell: bash
        run: |
          sed -i 's+/home/runner/work/hexagonal-architecture-python/hexagonal-architecture-python+/github/workspace+g' code-coverage-report/coverage.xml
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
